### ISSUE TITLE
英語のスペース?

### ISSUE THREAD

**Issue by fu7mu4** [hfukuchi/SPDX_specification#1]
ポリシー コンプライアンス、オープン ソースのように英語をカタカナ表記した場合に空白がありますが、あまり一般的ではないと思います。

**Comment by hfukuchi** [comment]
JTF日本語標準スタイルガイド（翻訳用）に従っています。

https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf

Linux Foundation Japanの翻訳Projectもこのスタイルガイドに従っていまして、今回同じスタイルを採用しました。
この情報は、READEMEに追記します。
