### ISSUE TITLE
Cross Referenceの日本語訳について

### ISSUE THREAD

**Issue by ghost** [hfukuchi/SPDX_specification#3]
下記の日本語訳をレビューしています。
https://github.com/hfukuchi/SPDX_specification/blob/master/review/spdxversion2.1_J_review_20180914.docx

5ページを確認したところ、License Cross Referenceをライセンス クロス参照と訳しています。
いくつかの辞書を調べたところ、Cross Referenceを相互参照もしくはクロスリファレンスまたはクロスレファレンスと訳す例が多かったです。
https://eow.alc.co.jp/search?q=cross-reference
https://ejje.weblio.jp/content/cross+reference

Cross Referenceをクロス参照と日本語訳した意図を教えてください。

**Comment by hfukuchi** [comment]
ご指摘をありがとうございます。
この単語はあまり調べずに訳しました。指摘された訳語（相互参照）を採用します。
